name = "babymak"
author = "jamesuki"
link = ""
year = 2021

[formats.standard]
matrix = [["_", "d", "h", "b", "_", "_", "m", "y", "_", "_"],
[",", "a", "a", "g", "!", "?", "w", "o", "o", "."],
["_", "l", "i", ":", ":", "p", "k", "_", "_", "_"]]

map = {}
home_row = 1
