name = "Colemak DHv"
author = "oats"
link = ""
year = 2021

[formats.standard]
matrix = [["q", "w", "c", "p", "b", "j", "l", "u", "y", ";", "-"],
["a", "r", "s", "t", "g", "m", "n", "e", "i", "o", "'"],
["z", "x", "f", "d", "k", "v", "h", "/", ".", ","]]

map = {}
home_row = 1
