name = "CTGAP 4.0"
author = "Colby Chai"
link = ""
year = 2022

[formats.standard]
matrix = [["q", "c", "l", "p", "v", "x", "k", "o", "u", "/"],
["r", "s", "n", "t", "g", "y", "h", "e", "i", "a"],
["z", "w", "m", "d", "b", "j", "f", "'", ",", "."]]

map = {}
home_row = 1
