name = "CTGAP 2.0"
author = "Colby Chai"
link = "github.com/CTGAP/ctgap-keyboard-layout"
year = 2021

[formats.standard]
matrix = [["w", "c", "l", "d", "k", "j", "y", "o", "u", "/"],
["r", "s", "t", "h", "m", "p", "n", "e", "i", "a"],
["q", "v", "g", "f", "b", "z", "x", "'", ",", "."]]

map = {}
home_row = 1
