name = "CTGAP 4.0"
author = "Colby Chai"
link = "github.com/CTGAP/ctgap-keyboard-layout"
year = 2022

[formats.standard]
matrix = [["x", "c", "l", "m", "k", "j", "y", "o", "u", "/"],
["r", "s", "t", "h", "b", "p", "n", "e", "i", "a"],
["q", "g", "w", "d", "v", "z", "f", "'", ",", "."]]

map = {}
home_row = 1
