name = "Heart"
author = "Heart"
link = "github.com/mindhatch/heart"
year = 2021

[formats.standard]
matrix = [["q", "c", "d", "v", "k", "j", "y", "o", "u", ";"],
["r", "s", "t", "h", "l", "p", "n", "a", "i", "e"],
["w", "g", "b", "m", "x", "z", "f", ",", ".", "/"]]

map = {}
home_row = 1
