name = "Dvorak"
author = "August Dvorak"
link = ""
year = 1936

[formats.standard]
matrix = [["v", "c", "w", "f", "q", "z", "p", "u", "o", "y", "/", "="],
["r", "d", "s", "h", "l", "k", "t", "e", "a", "i", "-"],
["x", "j", "m", "n", ";", "b", "g", "'", ",", "."]]

map = {}
home_row = 1
