name = "Rolll"
author = "semi"
link = "semilin.github.io/other_layouts.html"
year = 2021

[formats.standard]
matrix = [["y", "o", "u", "w", "b", "x", "k", "c", "l", "v"],
["i", "a", "e", "n", "p", "d", "h", "s", "r", "t"],
["j", "/", ",", ".", "q", "f", "m", "g", "'", "z"]]

map = {}
home_row = 1
