name = "RSTHD"
author = "xsznix"
link = "xsznix.wordpress.com/2016/05/16/introducing-the-rsthd-layout/"
year = 2016

[formats.standard]
matrix = [["j", "c", "y", "f", "k", "z", "l", ",", "u", "q", "="],
["r", "s", "t", "h", "d", "m", "n", "a", "i", "o", "'"],
["/", "v", "g", "p", "b", "x", "w", ".", ";", "-"],
[" ", " ", " ", " ", "e"]]

map = {}
home_row = 1
thumb_row = 3
