name = "Snug"
author = "mainstream"
link = ""
year = 2021

[formats.standard]
matrix = [
  ["x", "l", "d", "m", "b", "y", "w", "o", "u", "q"],
  ["s", "r", "t", "n", "f", "p", "c", "e", "i", "a"],
  ["z", "j", "k", "h", "v", "'", "g", "/", ",", "."],
]

map = {}
home_row = 1
