name = "Wreathy"
author = "Apsu"
link = ""
year = 2021

[formats.standard]
matrix = [["q", "g", "d", "f", "v", "j", "l", "u", "o", ","],
["n", "s", "t", "h", "y", "w", "r", "e", "a", "i"],
["b", "c", "m", "p", "k", "z", "x", "/", "'", "."]]

map = {}
home_row = 1
